apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: {{ .Name }}
  namespace: preview
spec:
  chart:
    name: go-test-flight
    repository: https://docker.wiseflow.io/chartrepo/k8s
    version: 0.1.0
  helmVersion: v3
  releaseName: "{{ .Name }}"
  values:
    image:
      tag: "{{ .Version }}"
    imagePullSecrets:
      - name: docker-credentials
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: 'true'
      enabled: true
      hosts:
        - host: "{{ .Name }}.stage.wiseflow.io"
          paths:
            - /
      labels: {}
      path: /
      tls:
        - hosts:
            - "{{ .Name }}.stage.wiseflow.io"
          secretName: "{{ .Name }}-tls"
    replicaCount: 1
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
