apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.valet.io/chart: semver:>=0.4.0
    hello: world
    valet.io/automated: "true"
  name: parrot-redis-ha
  namespace: parrot
spec:
  chart:
    name: appstream
    repository: https://dandydeveloper.github.io/charts
    version: 0.4.0
  helmVersion: v3
  releaseName: parrot-redis-ha
  values:
    redis:
      masterGroupName: parrot
    replicas: 4
    resources:
      limits:
        memory: 40Mi
      requests:
        cpu: 10m
        memory: 40Mi
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    hello: world
    valet.io/automated: "false"
  name: parrot-redis-ha
  namespace: parrot
spec:
  chart:
    name: redis-ha
    repository: https://dandydeveloper.github.io/charts
    version: 4.12.1
  helmVersion: v3
  releaseName: parrot-redis-ha
  values:
    redis:
      masterGroupName: parrot
    replicas: 4
    resources:
      limits:
        memory: 40Mi
      requests:
        cpu: 10m
        memory: 40Mi
